export const imagespackages = {
  group1729: require('./group1729.png'),
  ellipse: require('./ellipse.png'),
  icongoogle: require('./icongoogle.png'),
  Heart: require('./Heart.png'),
  Home: require('./Home.png'),
  Markey: require('./Markey.png'),
  Cart: require('./Cart.png'),
  info: require('./info.png'),
  person: require('./person.png'),
  lines: require('./lines.png'),
  bike: require('./bike.png'),
  map: require('./map.png'),
  Path: require('./Path.png'),
  gggg: require('./gggg.gif'),
  backarrow: require('./backarrow.png'),
  car: require('./car.png'),
  forward: require('./forward.png'),
  suit: require('./suit.png'),
  liner: require('./liner.png'),
};
